name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make

    - name: Deploy artifacts to Github
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: ./mod.zip

